version: "2.1"
services:
  tw-rfs-minio-server:
    image: "minio/minio:latest"
    command: [
        "minio",
        "server",
        "/data",
        "--address", ":9000",
        "--console-address", ":9001"
    ]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - tw-rfs-minio-data:/data
    environment:
      MINIO_ROOT_USER: "minio-local-admin"
      MINIO_ROOT_PASSWORD: "minio-local-admin-password"

volumes:
  tw-rfs-minio-data:
    name: tw-rfs-minio-data
    driver: local
